---
title: "Analysis Root area LTP PM 2025"
author: "Laura Gregoire"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
options(repos = c(CRAN = "https://cran.r-project.org"))
# install.packages("tinytex")
# tinytex::install_tinytex()
tinytex::is_tinytex()
rm(list = ls())
```


## STEPS :
- working directories, packages.. 

### import raw TR data 

```{r wd librairies}

library(ggplot2)
library(car)
library(ggpubr)
library(segmented)
library(pastecs)
library(dplyr)
library(patchwork)
library(RLRsim)
library(lme4)
library(inti)

here::here()

opPATH.obj= "./saved_objects/"
  if (!dir.exists(opPATH.obj)) dir.create(opPATH.obj, recursive = TRUE)


opPATH.results= "./results/"
  if (!dir.exists(opPATH.results)) dir.create(opPATH.results, recursive = TRUE)


opPATH.data= "./data/"
  if (!dir.exists(opPATH.data)) dir.create(opPATH.data, recursive = TRUE)


opPATH.fig= "./figures/"
  if (!dir.exists(opPATH.fig)) dir.create(opPATH.fig, recursive = TRUE)
```


```{r import data }
data <- read.csv(here::here(opPATH.data, "DATA_ROOT_TRAITS_LTP_2025.csv"), dec = ".", sep = ";")
panel <- read.csv(here::here(opPATH.data, "panel_pearl_millet.csv"), dec = ".", sep = ";")

data$PHENOTYPED = as.factor(data$PHENOTYPED)
# select only 4 rep , ie Phenotyped during week 1 or 2, but not both 1&2
data = data %>% filter(PHENOTYPED %in% c("1", "2"))
unique(data$PHENOTYPED)



data$GENO_TRT= paste(data$N_GENO, data$REPETITION, sep = "_")
data$GENO_TRT=as.factor(data$GENO_TRT)

data$N_GENO=as.factor(data$N_GENO)
data$REPETITION=as.factor(data$REPETITION) 
data$BLOCK=as.factor(data$BLOCK)
data$BLOCK_WEEK=as.factor(data$BLOCK_WEEK) 
data$WEEK=as.factor(data$WEEK)


data$LEAF_AREA=as.numeric(data$LEAF_AREA)
data$ROOT_AREA_TOTAL=as.numeric(data$ROOT_AREA_TOTAL)

nlevels(data$N_GENO)
nlevels(data$REPETITION)
nlevels(data$BLOCK)


save_before_cleaning = data
data=na.omit(data)


trial="LTP_PM_2025"
trait_name = "ROOT_AREA"
```



```{r }
print("phenotypic data loaded")
```





```{r variation before cleaning}
### boxplot to visualize variability among repetitions / BLOCK / WEEK ... 
ggplot(data, aes(x= data$REPETITION, y=data$ROOT_AREA_TOTAL)) + 
  geom_boxplot()

ggplot(data, aes(x= data$BLOCK, y=data$ROOT_AREA_TOTAL)) + 
  geom_boxplot()

ggplot(data, aes(x= data$BLOCK_WEEK, y=data$ROOT_AREA_TOTAL)) + 
  geom_boxplot()

ggplot(data, aes(x= data$WEEK, y=data$ROOT_AREA_TOTAL)) + 
  geom_boxplot()

ggplot(data, aes(x= data$ROOT_AREA_TOTAL, y=data$ROOT_AREA_TOTAL)) + 
  geom_boxplot()
```


```{r }
## sup outliers need to be removed (impossible values)
count_before = nrow(save_before_cleaning)
 data.RmOut <- data 

    out <- boxplot(data.RmOut$ROOT_AREA_TOTAL, plot = FALSE)$out # values to remove
    tf <- which(data.RmOut$ROOT_AREA_TOTAL %in% out) # position in the list
 data.RmOut$ROOT_AREA_TOTAL[tf] <- NA
    

    data.RmOut = na.omit(data.RmOut)
    count_after = nrow(data.RmOut)

out_tot = count_before - count_after
    
paste0("still ", nrow(data.RmOut), " observations on ",  nlevels(data.RmOut$N_GENO), " genotypes ", out_tot, " outliers removed")


```



### 3 : variability among repetitions
```{r outliers , eval=FALSE}
### boxplot to visualize variability among repetitions / BLOCK / WEEK ... 
ggplot(data.RmOut, aes(x= data.RmOut$REPETITION, y=data.RmOut$ROOT_AREA_TOTAL)) + 
  geom_boxplot()

ggplot(data.RmOut, aes(x= data.RmOut$BLOCK, y=data.RmOut$ROOT_AREA_TOTAL)) + 
  geom_boxplot()

ggplot(data.RmOut, aes(x= data.RmOut$BLOCK_WEEK, y=data.RmOut$ROOT_AREA_TOTAL)) + 
  geom_boxplot()


ggplot(data.RmOut, aes(x= data.RmOut$WEEK, y=data.RmOut$ROOT_AREA_TOTAL)) + 
  geom_boxplot()

ggplot(data.RmOut, aes(x= data.RmOut$ROOT_AREA_TOTAL, y=data.RmOut$ROOT_AREA_TOTAL)) + 
  geom_boxplot()




```



```{r sorting outliers}
    out <- boxplot(data.RmOut$ROOT_AREA_TOTAL, plot = FALSE)$out # values to remove
    tf <- which(data.RmOut$ROOT_AREA_TOTAL %in% out) # position in the list
 data.RmOut$ROOT_AREA_TOTAL[tf] <- NA
    

    data.RmOut = na.omit(data.RmOut)
    count_after = nrow(data.RmOut)

out_tot = count_before - count_after
    
paste0("still ", nrow(data.RmOut), " observations on ",  nlevels(data.RmOut$N_GENO), " genotypes ", out_tot, " outliers removed")


```

### 3 : variability among repetitions
```{r outliers after cleaning , eval=FALSE}
### boxplot to visualize variability among repetitions / BLOCK / WEEK ... 
ggplot(data.RmOut, aes(x= data.RmOut$REPETITION, y=data.RmOut$ROOT_AREA_TOTAL)) + 
  geom_boxplot()

ggplot(data.RmOut, aes(x= data.RmOut$BLOCK, y=data.RmOut$ROOT_AREA_TOTAL)) + 
  geom_boxplot()

ggplot(data.RmOut, aes(x= data.RmOut$BLOCK_WEEK, y=data.RmOut$ROOT_AREA_TOTAL)) + 
  geom_boxplot()


ggplot(data.RmOut, aes(x= data.RmOut$WEEK, y=data.RmOut$ROOT_AREA_TOTAL)) + 
  geom_boxplot()

ggplot(data.RmOut, aes(x= data.RmOut$ROOT_AREA_TOTAL, y=data.RmOut$ROOT_AREA_TOTAL)) + 
  geom_boxplot()




```





logical values ! let's continue with this dataset cleaned

```{r}

# save after cleaning
data = data.RmOut

```






```{r histogram cleaned data }
#Clean  data (remove NAs)
ROOT_AREA_TOTAL_values <- na.omit(data$ROOT_AREA_TOTAL)
df <- data.frame(ROOT_AREA_TOTAL = ROOT_AREA_TOTAL_values)
mean_ROOT_AREA_TOTAL <- mean(ROOT_AREA_TOTAL_values)
sd_ROOT_AREA_TOTAL <- sd(ROOT_AREA_TOTAL_values)

#Create histogram with normal curve using ggplot2
p <- ggplot(df, aes(x = ROOT_AREA_TOTAL)) +
  geom_histogram(aes(y = ..density..), bins = 30, fill = "lightblue", color = "black") +
  stat_function(fun = dnorm, args = list(mean = mean_ROOT_AREA_TOTAL, sd = sd_ROOT_AREA_TOTAL), color = "darkred", size = 1.2) +
  labs(
    title =  paste("Histogram of", trait_name, trial ),
    x = trait_name,
    y = "Density"
  ) +
  theme_minimal()



# Save the plot
ggsave(
  filename = paste0(opPATH.fig, "HIST_", trait_name, "_" ,trial,".png"),
  plot = p,
  width = 6,
  height = 4
)

print(p)

```

```{r variation among block rep }

ggplot(data, aes(x= data$WEEK, y=data$ROOT_AREA_TOTAL)) + 
  geom_boxplot()

ggplot(data, aes(x= data$BLOCK, y=data$ROOT_AREA_TOTAL)) + 
  geom_boxplot() # se


ggplot(data, aes(x= data$REPETITION, y=data$ROOT_AREA_TOTAL)) + 
  geom_boxplot()


ggplot(data, aes(x= data$BLOCK_WEEK, y=data$ROOT_AREA_TOTAL)) + 
  geom_boxplot()


```



```{r output }

write.table(x=data, file= paste0(opPATH.results, "values_cleaned_",trait_name,"_", trial, ".csv"), col.names = TRUE, row.names = FALSE, sep = ";")

```


```{r descriptive stat }
df_desc = as.data.frame(stat.desc(x=data$ROOT_AREA_TOTAL))

knitr::kable(df_desc, caption = paste("descriptive statistics", trial))
```

```{r anova among block rep}
model<-lm(ROOT_AREA_TOTAL~REPETITION, data = data)
aov<-Anova(model)
print(aov)


model<-lm(ROOT_AREA_TOTAL~BLOCK, data = data)
aov<-Anova(model)
print(aov)

model<-lm(ROOT_AREA_TOTAL~BLOCK_WEEK, data = data)
aov<-aov(model)
print(aov)


model<-lm(ROOT_AREA_TOTAL~WEEK, data = data)
aov<-Anova(model)
print(aov)
```

```{r}

model_RA <- lmer(
  ROOT_AREA_TOTAL ~ 1 + (1|N_GENO) + (1|REPETITION) + (1|BLOCK_WEEK),
  data = data,
  REML = TRUE
)
print(model_RA)

```


```{r}
model_RA_reduced <-lmer(
  ROOT_AREA_TOTAL ~ 1 + (1|REPETITION) + (1|BLOCK_WEEK),
  data = data,
  REML = TRUE
)
print(model_RA_reduced)
```


```{r}
anova(model_RA_reduced, model_RA)
```




# heritability : 

```{r heritability }
# --- Run H2cal analysis ---
data$REPETITION = as.factor(data$REPETITION)
data$BLOCK = as.factor(data$BLOCK)
# 

## -------------------------------
## Mixed model
## -------------------------------

library(agriutilities)
H2_cullis <- h_cullis(model_RA, genotype = "N_GENO", re_MME = FALSE)
print(H2_cullis)
save(H2_cullis, file =  paste0(opPATH.obj,"heritability_cullis_",trait_name,"_", trial, ".RData"))
write.table(H2_cullis, file = paste0(opPATH.results,"heritability_cullis",trait_name,"_", trial,  ".csv"), dec = ".", sep = ";")
```


```{r blups}
blup_geno <- ranef(model_RA)$N_GENO ## save blup

blup_result <-  blup_geno %>%
  tibble::rownames_to_column("N_GENO") %>% ## add n_geno id 
  rename(BLUP = `(Intercept)`)

  
  head(blup_result)

save(blup_result, file =  paste0(opPATH.obj,"BLUPS_",trait_name,"_", trial, ".RData"))  
write.table(blup_result, file = paste0(opPATH.results,"BLUPS_",trait_name, "_", trial, ".csv"), dec = ".", sep = ";")
```



```{r mean per geno}
ROOT_AREA_TOTAL_mean<-as.data.frame(with(data, tapply(data$ROOT_AREA_TOTAL, N_GENO, mean)))
  ROOT_AREA_TOTAL_mean = cbind(rownames(ROOT_AREA_TOTAL_mean),  ROOT_AREA_TOTAL_mean$`with(data, tapply(data$ROOT_AREA_TOTAL, N_GENO, mean))`)
colnames(ROOT_AREA_TOTAL_mean) = c("N_GENO", "ROOT_AREA")
ROOT_AREA_TOTAL_mean<-as.data.frame(ROOT_AREA_TOTAL_mean)
ROOT_AREA_TOTAL_mean$ROOT_AREA = as.numeric(ROOT_AREA_TOTAL_mean$ROOT_AREA)
ROOT_AREA_TOTAL_mean$N_GENO = as.factor(ROOT_AREA_TOTAL_mean$N_GENO)
nrow(ROOT_AREA_TOTAL_mean) # nb genotypes

## add genotypes names for future association studies


ROOT_AREA_TOTAL_mean <- merge(ROOT_AREA_TOTAL_mean, panel, by = "N_GENO", all.x = TRUE)

write.table(ROOT_AREA_TOTAL_mean, file = paste0(opPATH.results,trait_name, "_mean_", trial, ".csv"), dec = ".", sep = ";", row.names = FALSE)
```