---
title: "Analysis TE*plant* Lysimeter Pearl millet 2025"
author: "Laura Gregoire"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
options(repos = c(CRAN = "https://cran.r-project.org"))
tinytex::is_tinytex()
rm(list = ls())
```



```{r wd librairies, include=FALSE}
# install.packages("tinytex")
# tinytex::install_tinytex()


library(soiltestcorr)
library(segmented)
library("pastecs")
library("plyr")
library("car")
library("ggplot2")
library("multcomp")
library("lubridate")
library(reshape2)       
library(dplyr)     # data management
library(tidyr)
library(ggpubr)
library(pkr)
library(ggcorrplot)
library(corrplot)
library(stats)
library(agricolae)
library(lme4)
library("inti")
library(here)
library(RLRsim)

here::here()

opPATH.obj= "./saved_objects/"
  if (!dir.exists(opPATH.obj)) dir.create(opPATH.obj, recursive = TRUE)


opPATH.results= "./results/"
  if (!dir.exists(opPATH.results)) dir.create(opPATH.results, recursive = TRUE)


opPATH.data= "./data/"
  if (!dir.exists(opPATH.data)) dir.create(opPATH.data, recursive = TRUE)


opPATH.fig= "./figures/"
  if (!dir.exists(opPATH.fig)) dir.create(opPATH.fig, recursive = TRUE)


```


```{r load data, include=FALSE}
## import data 
data <- read.csv(here::here(opPATH.data, "DATA_TE_LYSI_PM_2025.csv"), dec = ".", sep = ";")
 panel <- read.csv(here::here(opPATH.data, "panel_pearl_millet.csv"), dec = ".", sep = ";")

#variables as factor studied
data$N_GENO=as.factor(data$N_GENO)
data$REPETITION=as.factor(data$REPETITION) 
data$BLOCK=as.factor(data$BLOCK)
data$TRENCH=as.factor(data$TRENCH)
data$GENO_TRT= paste(data$N_GENO, data$REPETITION, sep = "_")



data$LEAF_AREA=as.numeric(data$LEAF_AREA)
data$TOTDW_G=as.numeric(data$TOTDW_G)
data$TE=as.numeric(data$TE)

 save_before_cleaning = data
 
 trait_name = "TE"
 trial= "LYSI_PM_2025"
 
```


```{r, echo=FALSE}
print("libraries and phenotypic data loaded")
```

# variability among repetitions/block before cleaning : 

```{r variation before cleaning }
### boxplot to visualize variability among repetitions / BLOCK /  ... 
ggplot(data, aes(x= data$REPETITION, y=data$TE)) + 
  geom_boxplot()

ggplot(data, aes(x= data$BLOCK, y=data$TE)) + 
  geom_boxplot()

ggplot(data, aes(x= data$TRENCH, y=data$TE)) + 
  geom_boxplot()

```

# removed outliers :

```{r sorting outliers}
# there are one outlier at >7.5 g/kg ! 
count_before = nrow(data)

 data.RmOut <- data 


    for (i in 1:nrow(data.RmOut)) {
    data.RmOut$TE[i][data.RmOut$TE[i] > 7.5] <- NA

}


    data.RmOut = na.omit(data.RmOut)
    count_after = nrow(data.RmOut)
    
    
out_tot = count_before - count_after
    
paste0("still ", nrow(data.RmOut), " observations on ",  nlevels(data.RmOut$N_GENO), " genotypes ", out_tot, " outliers removed")
```

# variability among repetitions after cleaning : 

```{r outliers after cleaning}
### boxplot to visualize variability among repetitions / BLOCK /  ... 
ggplot(data.RmOut, aes(x= data.RmOut$REPETITION, y=data.RmOut$TE)) + 
  geom_boxplot()

ggplot(data.RmOut, aes(x= data.RmOut$BLOCK, y=data.RmOut$TE)) + 
  geom_boxplot()

ggplot(data.RmOut, aes(x= data.RmOut$TRENCH, y=data.RmOut$TE)) + 
  geom_boxplot()

```

# data distribution : 

```{r hist}

# save after cleaning
data = data.RmOut

te_values <- na.omit(data$TE)
df <- data.frame(TE = te_values)
mean_te <- mean(te_values)
sd_te <- sd(te_values)

# Create histogram with normal curve using ggplot2
p <- ggplot(df, aes(x = TE)) +
  geom_histogram(aes(y = ..density..), bins = 30, fill = "lightblue", color = "black") +
  stat_function(fun = dnorm, args = list(mean = mean_te, sd = sd_te), color = "darkred", size = 1.2) +
  labs(
    title = "Histogram of TEplant - Lysimeter 2025",
    x = "TEplant",
    y = "Density"
  ) +
  theme_minimal()

# Save the plot
ggsave(
  filename = paste(opPATH.fig, "HIST_", trait_name, "_", trial,".png"),
  plot = p,
  width = 6,
  height = 4
)

```

# variation among block rep : 


```{r anova among block rep}
model<-lm(TE~REPETITION, data = data)
aov<-Anova(model)
print(aov)

model<-lm(TE~BLOCK, data = data)
aov<-Anova(model)
print(aov)

model<-lm(TE~TRENCH, data = data)
aov<-aov(model)
print(aov)

```
# block significant
# variation among genotypes : 



 
 
```{r output }

write.table(x=data, file= paste0(opPATH.results, "values_cleaned_",trait_name,"_", trial, ".csv"), col.names = TRUE, row.names = FALSE, sep = ";")

```




```{r anova geno, include = TRUE}
# Fit the full model including N_GENO, BLOCK, and REPETITION as random effects
model_geno <- lmer(TE ~ 1 + (1 | N_GENO) + (1 | BLOCK) , data = data)
print(model_geno)
```


```{r anova without geno, include = TRUE}
# Fit the reduced model excluding N_GENO to see what's added by N_GENO
model_reduced <- lmer(TE ~ 1 + (1 | BLOCK) , data = data)
print(model_reduced)
```


```{r}
anova(model_geno, model_reduced)
```

# descriptive statistics :

```{r descriptive stat, echo = FALSE}
df_desc = as.data.frame(stat.desc(x=data$TE))

knitr::kable(df_desc, caption = "descriptive statistics TE")
```


# heritability : 

```{r heritability }
# Run heritability calculation
hr <- H2cal(
  data = data,
  trait = "TE",
  gen.name = "N_GENO",
  rep.n = 4,
  fixed.model = "0 + N_GENO + (1 | BLOCK) ",
  random.model = "1 + (1 | N_GENO) + (1 | BLOCK)",
  plot_diag = TRUE,
)

last_plot <- recordPlot()

df_output = as.data.frame(t(hr$tabsmr))

knitr::kable(df_output, caption = "Summary heritability estimates")

```

```{r heritability output}

# Save as image (PNG or PDF)

png(filename = here::here(paste0(opPATH.fig, "HERITABILITY_", trait_name, "_", trial, ".png")),
    width = 6, height = 4, units = "in", res = 300)
replayPlot(last_plot)
dev.off()
```



# blups :

```{r blups}

blup_result = as.data.frame(hr$blups)

blup_result <- merge(blup_result, panel,  by = "N_GENO")
  
save(blup_result, file =  paste0(opPATH.obj,"BLUPS_",trait_name, "_", trial, ".RData"))  
write.table(blup_result, file = paste0(opPATH.results,"BLUPS_",trait_name, "_", trial, ".csv"), dec = ".", sep = ";")
```
# mean per genotype :


```{r mean per geno}
TE_mean<-as.data.frame(with(data, tapply(data$TE, N_GENO, mean)))
  TE_mean = cbind(rownames(TE_mean),  TE_mean$`with(data, tapply(data$TE, N_GENO, mean))`)
colnames(TE_mean) = c("N_GENO", "TE")
TE_mean<-as.data.frame(TE_mean)
TE_mean$N_GENO = as.factor(TE_mean$N_GENO)
TE_mean <- merge(TE_mean, panel, by= "N_GENO")
write.table(TE_mean, file = paste0(opPATH.results,trait_name, "_mean_", trial, ".csv"), dec = ".", sep = ";", row.names = FALSE)


```



