---
title: "Plot ETref among experiments"
author: "Laura Gregoire"
date: "`r Sys.Date()`"
---

```{r}
library(ggplot2)
library(gridExtra)


```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)
options(repos = c(CRAN = "https://cran.r-project.org"))
# install.packages("tinytex")
# tinytex::install_tinytex()
tinytex::is_tinytex()
rm(list = ls())
```

```{r import data}
here::here()

opPATH.obj= "./saved_objects/"
  if (!dir.exists(opPATH.obj)) dir.create(opPATH.obj, recursive = TRUE)


opPATH.results= "./results/"
  if (!dir.exists(opPATH.results)) dir.create(opPATH.results, recursive = TRUE)


opPATH.data= "./data/"
  if (!dir.exists(opPATH.data)) dir.create(opPATH.data, recursive = TRUE)


opPATH.fig= "./figures/"
  if (!dir.exists(opPATH.fig)) dir.create(opPATH.fig, recursive = TRUE)

ETREF_HTP_LTP <- read.csv(here::here(opPATH.data, "ETREF_HTP_LTP.csv"), dec = ".", sep = ";", fileEncoding = "UTF-8" )
ETREF_LYSI <- read.csv(here::here(opPATH.data, "ETREF_LYSI.csv"), dec = ".", sep = ";",  fileEncoding = "UTF-8" )


ETREF_HTP_LTP$START_END = as.factor(ETREF_HTP_LTP$START_END)
ETREF_HTP_LTP$START_END <- factor(ETREF_HTP_LTP$START_END, levels = c( "8h-12h","12h-15h","15h-17h30","17h30-8h"))
ETREF_HTP_LTP$TRIAL = as.factor(ETREF_HTP_LTP$TRIAL)

ETREF_LYSI$SPECIES = as.factor(ETREF_LYSI$SPECIES)
ETREF_LYSI$DURATION = as.factor(ETREF_LYSI$DURATION)

levels(ETREF_HTP_LTP$TRIAL) 
#"HTP_SORGHUM"      "LTP_PEARL_MILLET" "LTP_SORGHUM"     
levels(ETREF_HTP_LTP$TRIAL) <- c(
  "High-tech Sorghum",
  "Low-tech PM",
  "Low-tech Sorghum"
)

levels(ETREF_LYSI$SPECIES) 
levels(ETREF_LYSI$SPECIES) <- c(
  "Lysimeter PM",
  "Lysimeter Sorghum"
)


```

```{r plot ETref}
# LTP_HTP = ETREF_all_trials 
# LTP_HTP = na.omit(LTP_HTP$ET_MM_DAY)
p1 <- 
  ggplot(data = ETREF_HTP_LTP, aes(x = TRIAL, y = ETREF_MM_HOUR, color = START_END)) +
  geom_point(size = 1, aes(group = START_END))+
  labs(x= NULL,
        y = expression(ET[ref] ~ (mm %.% h^{-1})),
       color = "Interval (hour)") +
     scale_y_continuous(
  breaks = seq(0, 0.8, 0.1)
 )+
 theme(axis.text.x = element_text(angle = 45, hjust = 1))+
   theme(text = element_text(size = 8))



p2 <- ggplot(data = ETREF_LYSI, aes(x = SPECIES, y = ETREF_MM_DAY, colour = DURATION)) + geom_point(size = 1,aes(group = DURATION)) +
  
  labs(x=NULL,y =expression(ET[ref] ~ (mm %.% day^{-1})), color = "Interval (day)") + theme(axis.text.x = element_text(size = 8, angle = 45, hjust = 1))+ scale_y_continuous(breaks = seq(0, 17, 0.5)) +   theme(text = element_text(size = 8))

  
  
plot_ETREF=grid.arrange(p1, p2, ncol = 2)



#Save the plot
ggsave(
  filename = "figures/ETREF_each_trial.png",
  plot = plot_ETREF,
  width = 6,
  height = 4
)

```

```{r}

tab_summary_LTP_HTP = aggregate(ETREF_MM_HOUR ~ TRIAL, data = ETREF_HTP_LTP,
          FUN = function(x) c(min = min(x, na.rm = TRUE),
                              mean = mean(x, na.rm = TRUE),
                              max = max(x, na.rm = TRUE)))


print(tab_summary_LTP_HTP)

```

```{r}
tab_summary_LTP_HTP_HOUR <- aggregate(
  ETREF_MM_HOUR ~ TRIAL + START_END,
  data = ETREF_HTP_LTP,
  FUN = function(x) c(
    min  = min(x, na.rm = TRUE),
    mean = mean(x, na.rm = TRUE),
    max  = max(x, na.rm = TRUE)
  )
)


```


```{r}

tab_summary_LYSI = aggregate(ETREF_MM_DAY ~ SPECIES, data = ETREF_LYSI,
          FUN = function(x) c(min = min(x, na.rm = TRUE),
                              mean = mean(x, na.rm = TRUE),
                              max = max(x, na.rm = TRUE)))


print(tab_summary_LYSI)

```

```{r}

tab_summary_LYSI_INTERVAL = aggregate(ETREF_MM_DAY ~ SPECIES+ DURATION_DAY, data = ETREF_LYSI,
          FUN = function(x) c(min = min(x, na.rm = TRUE),
                              mean = mean(x, na.rm = TRUE),
                              max = max(x, na.rm = TRUE)))


print(tab_summary_LYSI_INTERVAL)
```






